### ISSUE TITLE
event error?

### ISSUE THREAD

**Issue by ajonp** [nestlabs/rest-streaming#7]
Listening on port 80
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

Listening on port 80
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

[npm-debug.txt](https://github.com/nestlabs/rest-streaming/files/186874/npm-debug.txt)

**Comment by ajonp** [comment]
By removing this line it was successful...
openurl.open('http://localhost:' + port);
